import { KnowledgeGraph } from "./types";

/**
 * 示例知识图谱：一个前端工程师的知识图谱 demo 数据。
 */
export const sampleGraph: KnowledgeGraph = {
  nodes: [
    // 核心节点（大）
    {
      id: "javascript",
      label: "JavaScript",
      group: "frontend",
      size: 28,
      description: "Web开发核心语言，支撑前后端全栈开发",
    },
    {
      id: "react",
      label: "React",
      group: "frontend",
      size: 24,
      description: "声明式UI框架，组件化开发范式",
    },
    {
      id: "css",
      label: "CSS",
      group: "frontend",
      size: 20,
      description: "样式与布局，视觉呈现的基础",
    },
    {
      id: "nodejs",
      label: "Node.js",
      group: "backend",
      size: 20,
      description: "服务端JavaScript运行时",
    },
    {
      id: "typescript",
      label: "TypeScript",
      group: "frontend",
      size: 22,
      description: "JavaScript的类型超集，提供静态类型检查",
    },
    // 中等节点
    {
      id: "component",
      label: "组件化",
      group: "pattern",
      size: 16,
      description: "将UI拆分为独立可复用的组件",
    },
    {
      id: "design-pattern",
      label: "设计模式",
      group: "pattern",
      size: 18,
      description: "软件设计中的通用解决方案模板",
    },
    {
      id: "performance",
      label: "性能优化",
      group: "engineering",
      size: 16,
      description: "提升应用速度与用户体验",
    },
    {
      id: "state-mgmt",
      label: "状态管理",
      group: "frontend",
      size: 16,
      description: "管理应用中的数据流与状态变化",
    },
    {
      id: "api-design",
      label: "API设计",
      group: "backend",
      size: 14,
      description: "定义服务间通信的接口规范",
    },
    {
      id: "git",
      label: "Git",
      group: "engineering",
      size: 14,
      description: "分布式版本控制系统",
    },
    {
      id: "testing",
      label: "测试",
      group: "engineering",
      size: 14,
      description: "保障代码质量的自动化验证",
    },
    // 小节点
    {
      id: "hooks",
      label: "Hooks",
      group: "frontend",
      size: 12,
      description: "React函数组件的状态与副作用管理",
    },
    {
      id: "webpack",
      label: "Webpack",
      group: "engineering",
      size: 12,
      description: "模块打包工具，处理资源依赖与构建",
    },
    {
      id: "nextjs",
      label: "Next.js",
      group: "frontend",
      size: 16,
      description: "React全栈框架，支持SSR/SSG",
    },
    {
      id: "responsive",
      label: "响应式设计",
      group: "frontend",
      size: 12,
      description: "适配不同屏幕尺寸的设计方法",
    },
    {
      id: "fp",
      label: "函数式编程",
      group: "pattern",
      size: 14,
      description: "以函数为核心的编程范式，强调不可变性",
    },
    {
      id: "rest",
      label: "REST",
      group: "backend",
      size: 12,
      description: "基于HTTP的API架构风格",
    },
    {
      id: "docker",
      label: "Docker",
      group: "engineering",
      size: 12,
      description: "容器化技术，标准化开发与部署环境",
    },
    {
      id: "algorithm",
      label: "算法",
      group: "pattern",
      size: 14,
      description: "解决计算问题的系统方法",
    },
    {
      id: "tailwind",
      label: "Tailwind CSS",
      group: "frontend",
      size: 14,
      description: "实用类优先的CSS框架",
    },
    {
      id: "graphql",
      label: "GraphQL",
      group: "backend",
      size: 12,
      description: "灵活的API查询语言",
    },
  ],
  edges: [
    { source: "javascript", target: "react", relation: "是...的基础语言" },
    { source: "javascript", target: "nodejs", relation: "运行于" },
    { source: "javascript", target: "typescript", relation: "被...扩展" },
    { source: "javascript", target: "css", relation: "协同工作" },
    { source: "react", target: "component", relation: "核心思想" },
    { source: "react", target: "hooks", relation: "使用" },
    { source: "react", target: "state-mgmt", relation: "需要" },
    { source: "react", target: "nextjs", relation: "被...封装" },
    { source: "component", target: "design-pattern", relation: "属于" },
    { source: "design-pattern", target: "fp", relation: "包含" },
    { source: "typescript", target: "react", relation: "增强" },
    { source: "typescript", target: "nextjs", relation: "支持" },
    { source: "nodejs", target: "api-design", relation: "用于" },
    { source: "nodejs", target: "rest", relation: "实现" },
    { source: "api-design", target: "rest", relation: "遵循" },
    { source: "api-design", target: "graphql", relation: "可选方案" },
    { source: "css", target: "responsive", relation: "实现" },
    { source: "css", target: "tailwind", relation: "被...封装" },
    { source: "performance", target: "webpack", relation: "使用" },
    { source: "performance", target: "react", relation: "优化" },
    { source: "performance", target: "algorithm", relation: "基于" },
    { source: "git", target: "testing", relation: "配合" },
    { source: "docker", target: "nodejs", relation: "部署" },
    { source: "fp", target: "hooks", relation: "影响了" },
    { source: "testing", target: "react", relation: "验证" },
    { source: "nextjs", target: "tailwind", relation: "集成" },
    { source: "state-mgmt", target: "design-pattern", relation: "运用" },
  ],
};
